middleware/USAGE
middleware/index.js
package.json
test/middleware.test.js

/to @bajtos 
Depends on https://github.com/strongloop/loopback-workspace/pull/203

Add a generator for middleware

---

example/templates/common/models/location.js

1. Use Operation hooks instead of legacy model hooks
See strongloop/loopback-example-app@d281f7647
2. Fix lat and lng properties, they were reversed
See strongloop/loopback-example-app@6ef17f20d
3. Fix description for geo location
See strongloop/loopback-example-app@d94968d4d
See also https://github.com/strongloop/loopback-example-app/pull/68

Backport Location fixes from loopback-example-app

---

app/index.js
boot-script/index.js
lib/actions.js
package.json
test/app.test.js
test/common.js
test/example.test.js
test/helpers.test.js

/to @bajtos 
/cc @rmg 
The main effort is to upgrade to yeoman-generator 0.20.x which has quite a few breaking changes. This PR also fixes the build failure in master.

Upgrade deps to yeoman-generator 0.20.x

---

package.json
swagger/spec-loader.js
test/swagger.test.js
test/swagger/pet-store-2.0.yml

- Replaces https://github.com/strongloop/loopback-swagger/pull/8

[RFR] [PATCH] Feature/AddYmlSupport

---

lib/helpers.js
remote-method/USAGE
remote-method/index.js
test/common.js
test/remote-method.test.js

hey @bajtos, this is the first implementation of `remote-method generator` 
Further features are recorded in this issue: https://github.com/strongloop/generator-loopback/issues/94
Please review it when you have time. And I will add new fields and features in the near future.
Thanks a lot.

Remote method generator

---

property/index.js
remote-method/index.js
test/acl.test.js
test/property.test.js
test/relations.test.js

Extracted function `readJsonSync` to `/test/common.js`
and function `getTypeChoices` to `/lib/helpers.js`.
See details here:
Connect to strongloop/generator-loopback#128

Use shared function

---

.jshintrc
export-api-def/USAGE
export-api-def/index.js
package.json
test/export-api-def.test.js

Second part of the change for command line printing for swagger in loopback.
@bajtos Please review.
Connect to strongloop/loopback#1783

Add command line printing swagger definition to loopback

---

acl/index.js
lib/actions.js
property/index.js
relation/index.js

This pr is created for preventing users from creating a relation on a read-only model
Connect to strongloop/generator-loopback#103

Prevent readonly models in relation generator

---

app/index.js

Make `slc arc` conditional based on the cmd name

---

datasource/index.js

Use the metadata provided by loopback-workspace's `available-connectors` to ask the user a series of prompts to configure the datasource with connector-specific settings.
Example:
```
$ yo loopback:datasource
? Enter the data-source name: cds
? Select the connector for cds: IBM Cloudant DB (supported by StrongLoop)
Connector-specific configuration:
? database: mydb
? url: http://foobar.com/
? username:
? password:
? modelIndex:
```
Connect to #151 
/to @ritch please review
/cc @kraman

datasource: ask for connector-specific settings

---

datasource/index.js
lib/helpers.js
test/datasource.test.js

This PR adds support for object/array data source settings

Add support for object/array data source settings

---

datasource/index.js
package.json
test/datasource.test.js

Add the option to install connector modules on demand

---

swagger/spec-loader.js

This PR allows `.yaml` in addition to `.yml`

Use the correct regex to test yml/yaml extension

---

app/index.js

Update next steps text when running apic

Pare down next steps text when running apic.

---

model/index.js
test/model.test.js

This PR makes sure default base model is calculated correctly. We need to select the data source first.

Fix how default base model is set

---

model/index.js

Connect to https://github.com/strongloop/generator-loopback/issues/176

Add warning when no datasource available

---

package.json

This was added for the test/example file but that file was removed in 3ee309b71a1b49a27c1526d00420037ee4474070

remove glob devDep

---

remote-method/index.js

I had a discussion with another IBMer, a newbie to LoopBack, about creating models with custom remote methods. He was adding accepts/returns arguments by manually editing JSON files, because he did not realise the generator prompts were asking for arguments.
In this patch, I have reworded prompts and added more explanatory texts to guide new developers.
@richardpringle @crandmck @jannyHou please review
Here is a copy of the new generator output:
```
$ yo loopback:remote-method
? Select the model: Car
? Enter the remote method name: honk
? Is Static? Yes
? Description for method: make some noise!
Let's configure where to expose your new method in the public REST API.
You can provide multiple HTTP endpoints, enter an empty path when you are done.
? Enter the path of this endpoint: /honk
? …
```

remote-method: make prompts more descriptive

---

test/property.test.js

https://github.com/yeoman/generator/issues/600 has been fixed and released in `yeoman-generator@0.17.2`, we can remove the workarounds now.
Credit goes to @alexpit who noticed this first.
@alexpit please review

test: remove workarounds no longer needed

---

acl/index.js
app/index.js
boot-script/index.js
datasource/index.js
export-api-def/index.js
lib/actions.js
lib/helpers.js
middleware/index.js
model/index.js
package.json
property/index.js
relation/index.js
remote-method/index.js
swagger/index.js
test/acl.test.js
test/app.test.js
test/boot-script.test.js
test/datasource.test.js
test/export-api-def.test.js
test/help.test.js
test/middleware.test.js
test/model.test.js
test/property.test.js
test/relations.test.js
test/remote-method.test.js
test/swagger.test.js

Connect to https://github.com/strongloop/generator-loopback/issues/179

Update generator-loopback to yeoman 0.23

---

property/index.js
test/property.test.js

Validate the default-value type of a model property

---

property/index.js
test/property.test.js

Allow non required null defaults

---

app/index.js
datasource/index.js
package.json
property/index.js

* Missed globalizing a few warnings.
* Update to latest version of strong-globalize
* Fixed rootdir to use autonomousMsgLoading `all`

Missed globalizing some warnings

---

remote-method/index.js

Connect to https://github.com/strongloop/generator-loopback/issues/222

Fix generator not adding remote-method to json file

---

property/index.js

Fixes https://github.com/strongloop/loopback/issues/2891
@bajtos PTAL

Disable slc loopback:property for KeyValueModel

---

datasource/index.js

Connect to strongloop/generator-loopback#231
Details see https://github.com/strongloop/generator-loopback/issues/231#issuecomment-252158540

Reword message for custom connector

---

intl/es/loopback_boot-script_usage.txt
intl/es/loopback_export-api-def_usage.txt
intl/fr/loopback_app_usage.txt
intl/it/loopback_export-api-def_usage.txt

https://github.com/strongloop-internal/scrum-apex/issues/16

Update translation files

---

app/index.js

@crandmck PTAL. Thanks! :)
cc @cfjedimaster @emckean

Remove 'slc arc' from post install log

---

package.json
test/help.test.js
test/swagger.test.js

This allows us to start using ES6 syntax in the codebase.

Update to latest eslint and loopback config

---

app/index.js

Connect to strongloop-internal/scrum-loopback#1028

Add IBM branding to loopback-cli

---

lib/actions.js
package.json

See strongloop/eslint-config-loopback#19

Upgrade eslint-config, fix new violations

---

package.json
swagger/index.js
swagger/spec-loader.js
test/swagger.test.js

See https://github.com/strongloop/loopback-swagger/pull/81
https://github.com/strongloop/loopback-swagger/pull/81
- None

[SEMVER-MAJOR] Expose enhanced Swagger to LoopBack code generation to CLI

---

app/index.js
package.json

Removes the `yosay` banner.
- None

Remove yosay

---

soap/index.js

Usability improvement feedback from the demo which is to print the WSDL URL/file path once user selects the datasource. @raymondfeng PTAL

Print WSDL for the selected datasource

---

app/index.js
bluemix/helpers.js
bluemix/index.js
bluemix/login.js
datasource/index.js
package.json
test/bluemix.test.js
test/fixtures/help-texts/loopback_bluemix_help.txt
test/fixtures/help-texts/loopback_datasource_help.txt

Use API to log in on demand
- strongloop-internal/scrum-loopback#1536

Add on-demand bluemix login support

---

datasource/index.js
test/datasource.test.js

Fixes https://github.com/strongloop/generator-loopback/issues/285
- None

Fix undefined connector installation attempt

---

intl/it/loopback_bluemix_usage.txt
intl/it/loopback_datasource_usage.txt
intl/it/loopback_oracle_usage.txt

Update Italian translated strings Q2 2017
@0candy Please review
- None
- [x ] New tests added or existing tests modified to cover all changes
- [x ] Code conforms with the [style

Update Italian translated strings Q2 2017

---

bluemix/README.md

Added Bluemix authentication details

Added Bluemix authentication details

---

datasource/index.js
model/index.js
test/datasource.test.js

Add support for IBM Object Storage
- https://github.com/strongloop-internal/scrum-loopback/issues/1537

Support for IBM Object Storage

---

test/bluemix.test.js

Updated test to handle special case for datasources.bluemix.js
- None

Add test for datasources.bluemix.js

---

bluemix/login.js
package.json
test/bluemix.test.js

Fixes https://github.com/strongloop/generator-loopback/issues/302
- None

Add org and space info to config file

---

package.json

Updated `loopback-bluemix` to `3.0.0`.
- None

deps: loopback-bluemix@3.0.0

---

test/bluemix.test.js

Update test to check mandatory datasources-config.json file
- None

Update test to check datasources-config.json

---

model/index.js
test/model.test.js

Gracefully handle model errors
- None

Gracefully handle model errors

---

intl/es/messages.json

Updated the translated PII files from TVT first pass. 
- None

Update translations from TVT

---

package.json

@raymondfeng PTAL
Related PRs
- https://github.com/strongloop/loopback-swagger/pull/99 
- https://github.com/strongloop/loopback-component-explorer/pull/219
- https://github.com/strongloop/loopback-workspace/pull/496

Increment loopback-workspace to ^4.0.0

---

relation/index.js

Allow public flag to be undefined

---

package.json

Update yeoman-generator to have fix for a Uninitialized Memory Exposure
Vulnerability

chore: update dep

---

intl/it/messages.json

Related to #346 
Discussed with @candytangnb , it would be easier for us to abandon PR #346 and create this new one.

Fix Italian translation msg

---

oracle/index.js
package.json

Fix the following security vulnerability:
Command Injection
https://nodesecurity.io/advisories/663
See #352

Migrate from "open" to "opn"

---

intl/pl/messages.json

Polish translation check-in by YI TANG (tangyinb@cn.ibm.com) using WebFM tool.

[WebFM] pl translation Check-in by YI TANG (tangyinb@cn.ibm.com)

---

package.json

Remove support of node 6 since it's EOL in April 2019

chore: update node engine

---

export-api-def/index.js

- connect to strongloop/loopback-boot#291

run api generator after app is booted

---

.travis.yml

This is a follow-up for https://github.com/strongloop/generator-loopback/pull/406.

Travis: remove Node.js 6, add Node.js 12

---

package.json

Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/generator-loopback) 👈

update strong-soap version
