example/index.js
The project template in loopback-workspace 3.6.0-3.6.5 incorrectly
registers `loopback.status()` middleware via `middleware.json`.
Versions until 3.5.x and after 3.6.6 register the status route
from a boot script.
This patch modifies the example generator to support both flavours.
See also https://github.com/strongloop/loopback-workspace/pull/182 and #80
/to @raymondfeng or @ritch please review
=> example: support both flavours of status route

package.json, test/acl.test.js, test/app.test.js, test/datasource.test.js, test/end-to-end/example.e2e.js, test/example.test.js, test/model.test.js, test/property.test.js, test/relations.test.js, test/swagger.test.js
Use `generator.run(cb)` instead of `generator.run(opts, cb)`, since the latter no longer works.
=> Fix tests failing on the latest yeoman-generator

app/index.js, package.json, test/app.test.js
Use native `this.copy` when source file is not a directory. This allows us to
copy `gitignore` to `.gitignore` when scaffolding new projects.
=> Refactor `injectWorkspaceCopyRecursive`

example/templates/server/boot/create-sample-data.js, example/templates/server/sample-data/import.js, example/templates/server/test/rest-api.test.js, package.json
- Change `app.importing` to `app.booting`
- Use callbacks instead of emitting `import done`
- Replace `import done` event with the `ready` event
Connected to strongloop/generator-loopback#74
=> Use async features in example generator

boot-script/USAGE, boot-script/index.js, boot-script/templates/async.js, boot-script/templates/sync.js, test/boot-script.test.js
- Add code for `slc loopback:boot script` command
- Add unit tests
Connected to #90
=> Add boot script generator

app/index.js, test/app.test.js
Yeoman looks for `.yo-rc.json` (out-of-box) to determine the project root when
executing scripts. This means generators and sub-generator can be run in child
directories (not only from the project root).
Connected to strongloop-internal/scrum-loopback#207
=> Create .yo-rc.json when scaffolding new apps

model/index.js
Prevent "warning: possible EventEmitter memory leak detected" when adding more than 10 properties. This patch raises the limit to 256.
Fix #99 
/to @raymondfeng please review
/cc @lius
=> model: Prevent warning about EventEmitter leak

package.json, test/middleware.test.js
The problem was brought into light by
https://github.com/strongloop/loopback-workspace/pull/230
=> test/middleware: fix failure caused by typo

model/index.js
Adds a prompt to the model generator for selecting the model location. 
Options are 'common' or 'server', defaults to 'common'. 
Relates to #27.
=> Add Feature: Select Model Location

package.json
Update `yeoman-generator` to prevent spawn-sync warning.
=> Fix spawn-sync warning

lib/helpers.js, relation/index.js, test/helpers.test.js
Still work in progress.
Through this pull request I am trying to fix issue 118 (`https://github.com/strongloop/generator-loopback/issues/118`)
Mainly I added a validate function inside prompts to check the name conflict, all these changes happened in /relation/index.js
Fix #118
=> Make sure relation name different from property name

example/index.js, package.json, test/example.test.js
These assumptions break under npm@3 due to the flattening and
deduplication that is now done.
=> fix assumptions about dependency locations

test/help.test.js
43 passing (51s)
1 failing
1) loopback generator help "before each" hook: createSandbox for "print help message with yo by default":
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
=> Fix ci timeout error.

lib/helpers.js, property/index.js, relation/index.js, remote-method/index.js
Connect to strongloop-internal/scrum-loopback#642
Hey @bajtos this pr is created for preventing users naming a property as `constructor` in property, relation and remote method generators.
I use an array to contain reserved keywords in case we have more in the future, but now it only has `constructor`. 
Could you review it? Thanks!
=> Prevent constructor to be property name

model/index.js
Import the implementation of `generator#invoke` directly from `generator-yeoman/actions/invoke` to prevent a deprecation warning.
Fix #116
@jannyHou could you please verify that my solution proposed here works for you too?
/to @raymondfeng please review
=> Import `generator#invoke()` directly

lib/helpers.js
This will require apic cli side to set `process.env.SLC_COMMAND` to apic 
Reason being we cannot set `command` directly from `process.env.SLC_COMMAND` is [this use case](https://github.com/strongloop/generator-loopback/blob/master/test/help.test.js#L27)
and `exports.getCommandName` is treating `process.env.SLC_COMMAND` as a boolean flag
=> Helpers to display correct usage message for apic

remote-method/index.js
I should update remote-method generator together in this commit: https://github.com/strongloop/generator-loopback/commit/326102606476eef244102aaaf9104237d03c7823
One line's change, could you review it @bajtos , thanks :)
=> Only show editable model names in remote-method generator

app/index.js, package.json
When creating a new LoopBack project, let the user choose a template they would like to use.
When running from apiconnect CLI, remove "api-server" from the templates list and offer "hello-world" as the default template.
Requires https://github.com/strongloop/loopback-workspace/pull/255
/to @ritch please review
/cc @kraman
=> Add project template prompt, support apic

app/index.js
Add an option to suppress "next steps" banner, e.g. when running from a wrapper like `apic`.
/to @ritch please review
/cc @kraman
=> Add `yo loopback --skip-next-steps` options

remote-method/index.js
Related to : https://github.com/strongloop/loopback/issues/2070
In [remote-method](https://github.com/strongloop/generator-loopback/blob/master/remote-method/index.js#L160-L161) generator:
change `httpPath` to `path`
change `httpVerb` to `verb`
to make the setting work. `httpPath` and `httpVerb` are not recognized.
Otherwise remote method would use the default setting: `path`=methodname and `verb`=post
=> Use http and verb

app/index.js, package.json, test/app.test.js, test/common.js
Add a new CLI option to scaffold a project without the API Explorer component.
Requires https://github.com/strongloop/loopback-workspace/pull/257
Connect to #153 
/to @ritch please review
=> Implement `yo loopback --no-explorer`

model/index.js, test/model.test.js
/to @raymondfeng 
/cc @bajtos 
This fixes https://github.ibm.com/apimesh/scrum-platform-foundation/issues/344
```
Right now, if you dont select anything and hit enter, it fails
$ apic loopback => Empty app
$ apic create --type model
? Enter the model name: m5
? Select the data-source to attach m5 to: (Use arrow keys)
(no data-source)
readline.js:924
throw err;
^
```
=> Remove prompt for datasources when none exist

lib/actions.js, model/index.js, test/model.test.js
This PR has two fixes:
1. Make sure `null` data source is the last option of the list
2. Fix how default `db` is tested
3. Default to `db` if it exists, otherwise the first datasource
=> Fix data source ordier and default for models

property/index.js, test/property.test.js
adds a prompt for a default value when a new property is created on a model.  Currently, it supports the boolean values of true and false, the special cases of "guid", "uuid", "now" on date/datetime, as well as strings.  
I'm not super in love with this nested if/else structure, but since everything comes back from the command line as a string which we have to parse (based on the property's type), I'm not immediately seeing a better way to do this.  Additionally "guid", "uuid", and "now" are special cases as they set the property "defaultFn" as opposed to just "default".  It's not elegant, but it does work.
=> Prompt for Default Value on Property creation

lib/helpers.js, test/helpers.test.js
enhancement of pr https://github.com/strongloop/generator-loopback/pull/165#issuecomment-201057249
1. Check empty name in shared helper function validateName()
2. Add test case for rejecting empty name
3. remove duplicate checking of encodeURIComponent(name)
=> Check empty name in validateName and add testcase

remote-method/index.js
Doesn't break anything.  It shows up in the code sample output from `slc loopback:remote-method`.
ex:
```javascript
// We have added strong-remoting metadata for your new method to common/models/gift.json
// Now it's up to you to provide implementation in common/models/gift.js
// Here is a sample code to get you started:
/**
* List all available gifts
* @param {Function(Error, array)} callback
*/
Gift.listFree = funtion(callback) {
var gifts;
// TODO
callback(null, gifts);
};
```
=> typo 'funtion'

boot-script/index.js, datasource/index.js, lib/helpers.js, middleware/index.js, model/index.js, property/index.js, relation/index.js, remote-method/index.js, test/helpers.test.js
Add empty check to `validName` breaks remote-method generator, since in accept and return prompt, it checks validation before checking empty. 
I change the logic in remote-method generator so empty input could pass.
=> Fix accept and return to end with empty input

test/helpers.test.js
The tests were failing because there wasn't a `getAsync` method on the mocked out object
=> Fix failing relation name test

lib/helpers.js, remote-method/index.js, test/helpers.test.js, test/remote-method.test.js
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/813
- Update generator-loopback remote-method to make isStatic prompt not required. If not specified, it will default to true if method name does not contain `prototype.` and false otherwise.
- Add new validation for method name to allow for `prototype.` otherwise `.` is still invalid.
- Add unit test cases.
=> Allow defining remote method without isStatic flag

lib/helpers.js
https://github.com/strongloop/generator-loopback/pull/194#issue-158382178
Yeoman's inquirer validate is now called with two args (value and answers). See https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/base.js#L89
=> Fix generator prompt validate error

model/index.js
A small bug I noticed when I tried to create a model ...
Before:
After:
=> Fix "undefined" model name

app/index.js, package.json, test/app.test.js
Connect to strongloop/loopback#2344
Add a new prompt called `loopbackVersion` and pass it into [`createFromTemplate`](https://github.com/strongloop/generator-loopback/blob/master/app/index.js#L172)
```
{
name: 'loopbackVersion',
message: 'Which version of loopback do you want to install?',
default: 2.x,
choices: ['2.x', '3.x'],
}
```
=> Add prompt for lbVersion

datasource/index.js, test/datasource.test.js
Connect to strongloop/loopback#2265
Now when we choose a custom connector that not included in available connectors, it returns error.
This pr is created for supporting custom connector, and print a message to remind user manually add config then.
=> Support custom connector

lib/helpers.js, package.json, relation/index.js, test/helpers.test.js
Connect to strongloop/loopback#2505
Relation Name Check has a compatible problem with the latest yeoman generator.
Error details see:
```
jisoos-mbp:ji jisoolee$ apic loopback:relation
? Select the model to create the relationship from: Message
? Relation type: has many
? Choose a model to create a relationship with: Message
? Enter the property name for the relation: (messages) xyzErrorError: undefined
```
I believe it's caused by missing strongloop/generator-loopback@ba69e64
I apply that commit and the related test case here to fix it.
=> Replace-callback-with-promise

app/index.js
Improve the prompt for LoopBack version to tell the user what level of stability to expect from each version range.
I feel the current prompt does not give enough information to the user to make a good decision:
```
? Which version of LoopBack would you like to use? (Use arrow keys)
❯ 2.x
3.x
```
Here is the new prompt:
```
? Which version of LoopBack would you like to use? (Use arrow keys)
❯ 2.x (stable)
3.x (pre-release, alpha quality)
```
@jannyHou please review the implementation details
@ritch @crandmck @richardpringle please take a look at the additional text we are printing now and let me know how can we improve it.
=> app: describe stability of 2.x/3.x versions

property/index.js
Revert the behaviour change introduced by 950c8b, as it was confusing users.
I am intentionally not including a unit test, as I am not able to create a failing one. It seems that the mock prompt is converting empty strings to nulls under the hood, which bypasses the original check `if (required && defaultValue === '')`.
Connect to #213 
@0candy or @jannyHou: please review
=> Always allow properties with no default value

app/index.js, package.json
Connect to strongloop-internal/scrum-loopback#926
Related proposal: https://github.com/strongloop/generator-loopback/pull/207#issuecomment-227672375
In this pr:
[1]. I moved the loopbackVersion prompt before template, and get available LBVersions from loopback-workspace: [Workspace.getAvailableLBVersions()](https://github.com/strongloop/loopback-workspace/pull/290/files?diff=unified#diff-7bbb877b22354ec23e89bcd8cf629ed5R58)
[2]. I added a filter to choose templates based on it's supported LBVersion.
=> Add template filter

intl/en/messages.json, property/index.js
fixes https://github.com/strongloop/generator-loopback/issues/224
avoids scenario where generator ends up with `default: null` in date objects as they are not valid dates, it will now throw error which prompts user to enter the property again
=> property: Avoid casting invalid date into `null`

model/index.js
Do not prompt for properties when running `slc loopback:model` and choosing `KeyValueModel` as the base model.
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1074
@bajtos PTAL
=> Do not prompt for properties for KeyValueModel

lib/help.js, test/fixtures/help-texts/loopback_acl_help.txt, test/fixtures/help-texts/loopback_app_help.txt, test/fixtures/help-texts/loopback_boot-script_help.txt, test/fixtures/help-texts/loopback_datasource_help.txt, test/fixtures/help-texts/loopback_export-api-def_help.txt, test/fixtures/help-texts/loopback_middleware_help.txt, test/fixtures/help-texts/loopback_model_help.txt, test/fixtures/help-texts/loopback_property_help.txt, test/fixtures/help-texts/loopback_relation_help.txt, test/fixtures/help-texts/loopback_remote-method_help.txt, test/fixtures/help-texts/loopback_swagger_help.txt
Connect to strongloop/generator-loopback#227
Compared with the old one, the new generated help texts miss a space.
Fixing it in this pr.
Details see: https://github.com/strongloop/generator-loopback/issues/227#issuecomment-256066398
=> Add missing space in globalize help file

.travis.yml, package.json
Connect to strongloop/loopback#2807
Connect to strongloop-internal/scrum-loopback#1188
Note that I am intentionally picking 2.x as the next major version, because generator-loopback is not used by LoopBack applications and therefore there is no need to associate its major version number with LoopBack's major version. Also since we are in the middle of refactoring loopback-workspace, I expect there will be a new major version of generator-loopback coming soon.
cc @strongloop/loopback-dev @ritch @superkhau @jannyHou
=> Start 2.x + drop support for Node v0.10/v0.12

package.json, test/acl.test.js, test/mocha.opts
Add "test/mocha.opts" file specifying that "lib/globalize" should be loaded before starting any tests.
This is important to allow usage like `mocha test/help.test.js`.
The current workaround, where the first test file "test/acl.test.js" was initializing strong-globalize, was not sufficient.
Now that we have "test/mocha.opts", this patch also moves CLI flags from package.json's "test" script into this file.
=> Always require lib/globalize in tests

app/index.js, lib/help.js, lib/helpers.js, test/fixtures/help-texts/loopback_acl_help.txt, test/fixtures/help-texts/loopback_app_help.txt, test/fixtures/help-texts/loopback_export-api-def_help.txt, test/fixtures/help-texts/loopback_property_help.txt, test/fixtures/help-texts/loopback_relation_help.txt, test/help.test.js
In order to support the upcoming tool `loopback-cli`, we need to modify generator-loopback to recognize the new wrapper. This time it's more tricky, because we are not only replacing `yo` with e.g. `slc`, but also dropping `loopback:` prefix from generator names.
```
lb model -> yo loopback:model
```
Connect to strongloop-internal/scrum-loopback#1028
=> Add support for SLC_COMMAND="loopback-cli"

app/index.js
While fixing https://github.com/strongloop-internal/scrum-loopback/issues/1411, I noticed that the APIC promotion is not printed when the generator is run with `--skip-next-steps`.
In this patch, I am moving the APIC banner to a standalone method/async step, so that it is run even when next steps are skipped.
cc @smartmouse
=> Print IBM promotion even with --skip-next-steps

app/index.js
The generator still defaults to version 2.x rather than the current version 3.x
=> Update default LB version to 3.x

app/index.js, test/app.test.js
Export the version of workspace we are using to allow CLI tools to include workspace version in `--version` output.
- Required by https://github.com/strongloop/loopback-cli/pull/25
=> Export the version of workspace we are using

lib/actions.js, soap/README.md, soap/index.js, soap/wsdl-loader.js, test/soap.test.js
This PR has 
1)  support for  “lb soap” integration with SOAP WebServices datasource
2) support for updates if models already exist
3) Fixed Issue https://github.com/strongloop/loopback-cli/issues/28
4) Updated existing tests 
5) Updated README to point to loopback-cli README as single source of information. 
6) README in loopback-cli to change from WSDL URL - > datasource name will be done through another PR in loopback-cli repo
@raymondfeng PTAL
=> Integrate datasource with lb soap feature

soap/index.js, test/soap.test.js
@raymondfeng PTAL This PR:
- handles excludeBaseProperties from base 'Model' - This is for fixing strongloop/loopback-workspace#486 
- Also generates SOAP models under 'common' instead of 'server'
- Test case changes
=> Add excludeBaseProperties support

bluemix/login.js, package.json, test/app.test.js, test/bluemix.test.js, test/model.test.js
When cached BM config is not found, the tests fail due to login requests without this change.
- None
=> Add --login=false to avoid BM login for tests

bluemix/helpers.js, bluemix/index.js, datasource/index.js, intl/en/loopback_bluemix_usage.txt, test/fixtures/help-texts/loopback_bluemix_help.txt
Separate command for service provisioning
- None
=> Separate command for service provisioning

datasource/index.js, test/datasource.test.js
Crucial fields were missing in datasources.js for IBM Object Storage
- None
=> Add missing fields in datasources.js

test/datasource.test.js
Add tests for MongoDB and Cloudant support
- None
=> Add tests for MongoDB and Cloudant support

soap/index.js, test/soap.test.js, test/soap/special_char_test.wsdl
There are 2 bugs in this issue https://github.com/strongloop/loopback-connector-soap/issues/78 
and the first issue is fixed in this PR https://github.com/strongloop/loopback-soap/pull/7.  2nd issue is fixed with this current PR. We use binding name as top level REST API file/model filename and if special characters are present (e.g '.') which are not acceptable in filename, then, code generation fails with exception as reported in issue https://github.com/strongloop/loopback-connector-soap/issues/78 . This PR replaces special characters with underscore '_' . Also added test to cover this use case and cleaned up/refactored test code.
@raymondfeng PTAL
=> Handle special char in API filename

export-api-def/index.js, package.json, test/export-api-def.test.js
If the command `export-api-def` is ran on an app that has ongoing async calls and never returns, the loopback generator itself never returns, waiting for module to finish loading.
This fix exits the Node process as soon as swagger spec has been written
WIP because for now I'm not sure how to test this fix. 
- strongloop/loopback-cli/issues/50
=> Fix export-api-def hanging if project contains ongoing async operations

relation/index.js, test/relations.test.js
Prompt users to confirm `disableInclude` and `nestRemoting` options when a relation is defined.
=> Allow disableInclude and nestRemoting options

package.json
Update `loopback-swagger` version in `package.json`, because the latest changes in `loopback-swagger` are not picked up by `loopback-cli`.
connect to: https://github.com/strongloop/loopback-swagger/issues/111
=> update loopback-swagger dependencies

package.json, swagger/spec-loader.js, test/swagger/pet-store-1.2.json, test/swagger/pet-store-2.0.json, test/swagger/pet-store-2.0.yml
The PR use `swagger-parser` to resolve `$ref` for Swagger 2.0 docs.
Depends on https://github.com/strongloop/loopback-swagger/pull/114
=> Improve $ref support for swagger objects

intl/en/loopback_zosconnectee_usage.txt, package.json, test/zosconnectee.test.js, test/zosconnectee/swagger.json, zosconnectee/README.md, zosconnectee/index.js
Add a new command, `zosconnectee` to the `lb` command which:
1. Connects to the z/OS Connect EE server for a specified datasource
2. Retrieves the list of available APIs
3. Retrieves the Swagger document for the selected API and configures the Datasource
- strongloop/loopback-cli#43
=> Add z/OS Connect EE command

bluemix/helpers.js, bluemix/index.js, test/fixtures/help-texts/loopback_bluemix_help.txt
Allow appName to be passed as an option for automated (non-prompted) usage.
=> feat: Allow appName to be passed in as options

app/index.js, test/app.test.js
Now we can use lb --loopbackVersion 3.x --template notes to scaffold an
app without prompting such questions.
- connect to https://github.com/strongloop/loopback-cli/issues/61
=> Add loopbackVersion and template options to skip prompts

boot-script/templates/async.js, boot-script/templates/sync.js, swagger/README.md
> There are links to docs.strongloop.com in various places in the code that we should replace with links to the new doc site loopback.io/doc
There are 3 links that are fixed in this PR, and the rests are formatting changes from running the linter:
- boot-script/templates/async.js
- boot-script/templates/sync.js
- swagger/README.md
connected to: https://github.com/strongloop-internal/scrum-loopback/issues/1108
=> docs: update links from docs.strongloop.com

app/index.js
Add `--version` to the list of options when displaying help.
- connect to strongloop/loopback-cli#35
=> Add --version to help options

app/index.js, bluemix/index.js, bluemix/login.js, datasource/index.js, middleware/index.js, model/index.js, oracle/index.js, package.json, remote-method/index.js, soap/index.js, swagger/index.js, test/acl.test.js, test/app.test.js, test/bluemix.test.js, test/datasource.test.js, test/export-api-def.test.js, test/fixtures/help-texts/loopback_app_help.txt, test/middleware.test.js, test/property.test.js, test/relations.test.js, test/remote-method.test.js, test/soap.test.js, test/zosconnectee.test.js, zosconnectee/index.js
Fixes #354 
Please take a look at just the first commit; the second is linting and eslint dependency upgrades
=> Fix failing tests

model/index.js, test/model.test.js
Fixing the test failure in https://github.com/strongloop/loopback-cli/pull/71, it's also a missing feature.
https://github.com/strongloop/loopback-cli/issues/76
=> honor app name in arguments

test/app.test.js
Change the order from [2.x, 3.x] to [3.x, 2.x] to match the actual
behavior.
This is a partial back-port of #399
=> Fix the expected list of supported LB versions [5.x]

app/index.js, package.json, test/app.test.js, test/fixtures/help-texts/loopback_app_help.txt, test/remote-method.test.js
After the PR https://github.com/strongloop/loopback-workspace/pull/549 to remove LB2.x version in the loopback-workspace, there are a few tests failure.  
The major changes are in the `remote-method.test.js`.  Following what @bajtos provided in this comment https://github.com/strongloop/loopback-workspace/pull/549#issuecomment-489141430, I've made the changes in this repo accordingly. 
- https://github.com/strongloop/loopback-workspace/pull/549
- https://github.com/strongloop/loopback/issues/4180
=> Fix tests after removing 2.x in workspace

boot-script/index.js, swagger/index.js, test/boot-script.test.js, test/swagger.test.js
`lb swagger` and `lb boot-script` should honour the arguments.
Remove blocker for https://github.ibm.com/apimesh/apiconnect-cli-loopback/pull/132/
- connect to https://github.ibm.com/apimesh/apiconnect-cli-loopback/pull/132/
=> fix: honor the argument

middleware/index.js, remote-method/index.js, test/middleware.test.js, test/remote-method.test.js
Similar to https://github.com/strongloop/generator-loopback/pull/408
Honor the arguments in the remote method and middleware commands.
=> fix: arguments for 2 commands

model/index.js, property/index.js, test/model.test.js
connect to https://github.ibm.com/apimesh/apiconnect-cli-loopback/issues/138
APIC cannot invoke the loop of property generator when run the model generator. 
In the previous implementation, invoking `.composeWith()` inside `.prompt()` cannot finish execution when `env.run()` takes in a cb function. For details please check the conversation in the related issue.
This PR moves the "property name prompt" and "empty property check" **from model generator to  property generator**, so that the composed generator won't be affected by `this.prompt()`.
*Test:* we don't test composed generator(actually there is no way to test it), so I manually verified the cli on local:
installed `loopback-cli` globally and npm link the `generator-loopback` inside it
```
(1) create a model with multiple properties …
```
=> move property name check to property generator

package.json, test/soap.test.js, test/soap/DataService_model_array.wsdl, test/soap/DataService_string_array.wsdl
Related to PR: https://github.com/strongloop/loopback-soap/pull/31 
Related to issue: https://github.com/strongloop/loopback-soap/issues/32
The tests for the generated API code are placed in `loopback-soap`.
The tests for the generated models are placed in `generator-loopback`.
My fix to issue https://github.com/strongloop/loopback-soap/issues/32 didn't involve arrays, but I was asked to make sure my fix in https://github.com/strongloop/loopback-soap/pull/31 could handle arrays.
Extra tests had to be added in this repository regarding models generated from WSDL files that have arrays in the operation input and/or output.
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/generator-loopback) 👈
=> add tests for arrays in generation of soap models

package.json
- deps: update mkdirp to ^1.0 to fix #416
- chore: update mocha to latest  - get rid of Prototype Pollution problem in minimist (see https://www.npmjs.com/advisories/1179)
Quoting from `mkdirp` release notes (see the full list of changes [here](https://github.com/isaacs/node-mkdirp/blob/master/CHANGELOG.md#10)):
> Drop support for outdated Node.js versions. (Technically still works on Node.js v8, but only 10 and above are officially supported.)
This package (`generator-loopback`) has `engines.node` set to `>=8`, but we officially don't support EOL version of Node.js and our tests are passing on Node.js 8.x with the new version of `mkdirp` too, so I guess this upgrade should be ok 🤞 
Also note that there are 25 more outdated dependencies, but considering that this package is in Maintenance …
=> Update dependencies (mkdirp, mocha)
